"""auto-generated migration

Revision ID: 101c53e398bc
Revises: 
Create Date: 2023-07-03 03:48:10.851416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101c53e398bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('institutionID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('institutionName', sa.String(length=255), nullable=False),
    sa.Column('institutionAddress', sa.Text(), nullable=False),
    sa.Column('emailID', sa.String(length=255), nullable=False),
    sa.Column('contactNum', sa.String(length=10), nullable=False),
    sa.Column('membership', sa.Enum('Choice1', 'Choice2'), nullable=False),
    sa.PrimaryKeyConstraint('institutionID'),
    sa.UniqueConstraint('institutionName')
    )
    op.create_table('users',
    sa.Column('userID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('roleID', sa.Enum('SuperAdmin', 'Admin', 'Coordinator', 'Editor', 'AssociateEditor', 'Reviewer', 'Author'), nullable=True),
    sa.Column('institutionID', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['institutionID'], ['institutions.institutionID'], ),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conferences',
    sa.Column('conferenceID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conferenceTheme', sa.String(length=255), nullable=False),
    sa.Column('inCharge', sa.BigInteger(), nullable=False),
    sa.Column('conferenceTrack', sa.String(length=255), nullable=False),
    sa.Column('chairDesignation', sa.String(length=255), nullable=False),
    sa.Column('chairName', sa.String(length=255), nullable=False),
    sa.Column('coChairDesignation', sa.String(length=255), nullable=True),
    sa.Column('conferenceBoardDesignation', sa.String(length=255), nullable=True),
    sa.Column('conferenceBoardName', sa.String(length=255), nullable=True),
    sa.Column('organizingCommittee', sa.String(length=255), nullable=True),
    sa.Column('internationalAdvisoryBoard', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inCharge'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('conferenceID')
    )
    op.create_table('conference_associate_editors',
    sa.Column('conferenceAssociateEditorID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('associateEditorID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['associateEditorID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['conferenceID'], ['conferences.conferenceID'], ),
    sa.PrimaryKeyConstraint('conferenceAssociateEditorID'),
    sa.UniqueConstraint('associateEditorID')
    )
    op.create_table('conference_editors',
    sa.Column('conferenceEditorID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('editorID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conferences.conferenceID'], ),
    sa.ForeignKeyConstraint(['editorID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('conferenceEditorID'),
    sa.UniqueConstraint('editorID')
    )
    op.create_table('conference_reviewers',
    sa.Column('conferenceReviewerID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('reviewerID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conferences.conferenceID'], ),
    sa.ForeignKeyConstraint(['reviewerID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('conferenceReviewerID'),
    sa.UniqueConstraint('reviewerID')
    )
    op.create_table('conference_roster',
    sa.Column('rosterID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('authorID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['authorID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['conferenceID'], ['conferences.conferenceID'], ),
    sa.PrimaryKeyConstraint('rosterID')
    )
    op.create_table('events',
    sa.Column('eventID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('eventName', sa.String(length=255), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('regOpen', sa.DateTime(), nullable=False),
    sa.Column('regClose', sa.DateTime(), nullable=False),
    sa.Column('eventStart', sa.DateTime(), nullable=False),
    sa.Column('eventEnd', sa.DateTime(), nullable=False),
    sa.Column('maxParticipants', sa.Integer(), nullable=True),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conferences.conferenceID'], ),
    sa.PrimaryKeyConstraint('eventID'),
    sa.UniqueConstraint('eventName')
    )
    op.create_table('submissions',
    sa.Column('submissionID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ifPubApplicable', sa.Boolean(), nullable=False),
    sa.Column('plagPolicy', sa.Integer(), nullable=False),
    sa.Column('samplePaper', sa.String(length=255), nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('submissionDeadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conferences.conferenceID'], ),
    sa.PrimaryKeyConstraint('submissionID')
    )
    op.create_table('papers',
    sa.Column('paperID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paperName', sa.String(length=255), nullable=False),
    sa.Column('authorID', sa.BigInteger(), nullable=False),
    sa.Column('paperLink', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['authorID'], ['conference_roster.authorID'], ),
    sa.PrimaryKeyConstraint('paperID')
    )
    op.create_table('paper_status',
    sa.Column('statusID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paperID', sa.BigInteger(), nullable=False),
    sa.Column('isFinalRevision', sa.Boolean(), nullable=False),
    sa.Column('toPublish', sa.Boolean(), nullable=False),
    sa.Column('presentationStatus', sa.Enum('Accept', 'Reject', 'Soft Accept', 'Soft Reject'), nullable=False),
    sa.ForeignKeyConstraint(['paperID'], ['papers.paperID'], ),
    sa.PrimaryKeyConstraint('statusID')
    )
    op.create_table('submitted_papers',
    sa.Column('submittedPaperID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submissionID', sa.BigInteger(), nullable=False),
    sa.Column('paperID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['paperID'], ['papers.paperID'], ),
    sa.ForeignKeyConstraint(['submissionID'], ['submissions.submissionID'], ),
    sa.PrimaryKeyConstraint('submittedPaperID', 'submissionID', 'paperID')
    )
    op.create_table('paper_revisions',
    sa.Column('revisionID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('revisionNumber', sa.Integer(), nullable=False),
    sa.Column('revisionLink', sa.String(length=255), nullable=False),
    sa.Column('revisionDateTime', sa.DateTime(), nullable=False),
    sa.Column('submittedPaperID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['submittedPaperID'], ['submitted_papers.submittedPaperID'], ),
    sa.PrimaryKeyConstraint('revisionID')
    )
    op.create_table('reviews',
    sa.Column('reviewID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('editorID', sa.BigInteger(), nullable=False),
    sa.Column('associateEditorID', sa.BigInteger(), nullable=True),
    sa.Column('reviewerID', sa.BigInteger(), nullable=False),
    sa.Column('revisionID', sa.BigInteger(), nullable=False),
    sa.Column('process', sa.Enum('Single Blind Review', 'Double Blind Review'), nullable=False),
    sa.Column('reviewEndDeadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['associateEditorID'], ['conference_associate_editors.conferenceAssociateEditorID'], ),
    sa.ForeignKeyConstraint(['editorID'], ['conference_editors.conferenceEditorID'], ),
    sa.ForeignKeyConstraint(['reviewerID'], ['conference_reviewers.conferenceReviewerID'], ),
    sa.ForeignKeyConstraint(['revisionID'], ['paper_revisions.revisionID'], ),
    sa.PrimaryKeyConstraint('reviewID')
    )
    op.create_table('review_comments',
    sa.Column('reviewCommentID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reviewID', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('commentDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewID'], ['reviews.reviewID'], ),
    sa.PrimaryKeyConstraint('reviewCommentID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_comments')
    op.drop_table('reviews')
    op.drop_table('paper_revisions')
    op.drop_table('submitted_papers')
    op.drop_table('paper_status')
    op.drop_table('papers')
    op.drop_table('submissions')
    op.drop_table('events')
    op.drop_table('conference_roster')
    op.drop_table('conference_reviewers')
    op.drop_table('conference_editors')
    op.drop_table('conference_associate_editors')
    op.drop_table('conferences')
    op.drop_table('users')
    op.drop_table('institutions')
    # ### end Alembic commands ###
