"""auto-generated migration

Revision ID: fd2a6e306086
Revises: 
Create Date: 2023-07-05 09:10:52.510719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2a6e306086'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('institutionName', sa.String(length=255), nullable=False),
    sa.Column('institutionAddress', sa.Text(), nullable=False),
    sa.Column('emailID', sa.String(length=255), nullable=False),
    sa.Column('contactNum', sa.String(length=10), nullable=False),
    sa.Column('membership', sa.Enum('Choice1', 'Choice2'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institutionName')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('roleID', sa.Enum('SuperAdmin', 'Admin', 'Coordinator', 'Editor', 'AssociateEditor', 'Reviewer', 'Author'), nullable=True),
    sa.Column('institutionID', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institutionID'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('institution')
    # ### end Alembic commands ###
